export default {
  className:
    "popout-container popout-f22f85e9-36bf-41c1-aa56-269f44a2c153-container",
  title: "Editor",
  uuid: "popout-f22f85e9-36bf-41c1-aa56-269f44a2c153",
  container: "popout-f22f85e9-36bf-41c1-aa56-269f44a2c153-container",
  initialPosition: {
    x: 1432,
    y: 35,
    left: 0,
    width: 1611,
    top: 0,
    height: 913,
  },
  clickParent: { 0: {}, length: 1 },
  focusId: "content_blocks.0",
  panelFocusModel: { focused: "content_blocks.0", "content_blocks.0": true },
  titleViewArguments: {
    model: {
      "@id": "c41f6355-56b9-41ce-9cc3-e96a8ae46116",
      _bookshop_name: {
        "@id": "content_blocks._bookshop_name",
        value: "privacy/hero",
        "@keys": ["value"],
        "@flat": true,
        "@initialValue": { value: "privacy/hero" },
      },
      title: {
        "@id": "content_blocks.title",
        value: "Terms & Conditions",
        "@keys": ["value"],
        "@flat": true,
        "@initialValue": { value: "Terms & Conditions" },
      },
      "@keys": ["_bookshop_name", "title"],
      "@flat": false,
      "@initialValue": {
        _bookshop_name: "privacy/hero",
        title: "Terms & Conditions",
      },
    },
  },
  childViewArguments: {
    model: {
      _schema: {
        "@id": "_schema",
        value: "default",
        "@keys": ["value"],
        "@flat": true,
        "@initialValue": { value: "default" },
      },
      title: {
        "@id": "title",
        value: "Privacy",
        "@keys": ["value"],
        "@flat": true,
        "@initialValue": { value: "Privacy" },
      },
      seo: {
        "@id": "seo",
        page_description: {
          "@id": "seo.page_description",
          value: null,
          "@keys": ["value"],
          "@flat": true,
          "@initialValue": { value: null },
        },
        canonical_url: {
          "@id": "seo.canonical_url",
          value: null,
          "@keys": ["value"],
          "@flat": true,
          "@initialValue": { value: null },
        },
        featured_image: {
          "@id": "seo.featured_image",
          value: null,
          "@keys": ["value"],
          "@flat": true,
          "@initialValue": { value: null },
        },
        featured_image_alt: {
          "@id": "seo.featured_image_alt",
          value: null,
          "@keys": ["value"],
          "@flat": true,
          "@initialValue": { value: null },
        },
        author_twitter_handle: {
          "@id": "seo.author_twitter_handle",
          value: null,
          "@keys": ["value"],
          "@flat": true,
          "@initialValue": { value: null },
        },
        open_graph_type: {
          "@id": "seo.open_graph_type",
          value: null,
          "@keys": ["value"],
          "@flat": true,
          "@initialValue": { value: null },
        },
        no_index: {
          "@id": "seo.no_index",
          value: false,
          "@keys": ["value"],
          "@flat": true,
          "@initialValue": { value: false },
        },
        "@keys": [
          "page_description",
          "canonical_url",
          "featured_image",
          "featured_image_alt",
          "author_twitter_handle",
          "open_graph_type",
          "no_index",
        ],
        "@flat": false,
        "@initialValue": {
          page_description: null,
          canonical_url: null,
          featured_image: null,
          featured_image_alt: null,
          author_twitter_handle: null,
          open_graph_type: null,
          no_index: false,
        },
      },
      content_blocks: {
        "@id": "content_blocks",
        value: [
          {
            "@id": "c41f6355-56b9-41ce-9cc3-e96a8ae46116",
            _bookshop_name: {
              "@id": "content_blocks._bookshop_name",
              value: "privacy/hero",
              "@keys": ["value"],
              "@flat": true,
              "@initialValue": { value: "privacy/hero" },
            },
            title: {
              "@id": "content_blocks.title",
              value: "Terms & Conditions",
              "@keys": ["value"],
              "@flat": true,
              "@initialValue": { value: "Terms & Conditions" },
            },
            "@keys": ["_bookshop_name", "title"],
            "@flat": false,
            "@initialValue": {
              _bookshop_name: "privacy/hero",
              title: "Terms & Conditions",
            },
          },
          {
            "@id": "35a4dfae-0083-482e-9e54-7427f7b6ad95",
            _bookshop_name: {
              "@id": "content_blocks._bookshop_name",
              value: "privacy",
              "@keys": ["value"],
              "@flat": true,
              "@initialValue": { value: "privacy" },
            },
            terms_and_conditions: {
              "@id": "content_blocks.terms_and_conditions",
              value: [
                {
                  "@id": "4d7be7fe-491e-469c-8717-fb0656f1ed0f",
                  heading: {
                    "@id": "content_blocks.terms_and_conditions.heading",
                    value: "Sendit Terms And Conditions",
                    "@keys": ["value"],
                    "@flat": true,
                    "@initialValue": { value: "Sendit Terms And Conditions" },
                  },
                  description: {
                    "@id": "content_blocks.terms_and_conditions.description",
                    value:
                      "<p>By using Sendit, you agree to the terms and conditions listed on this page.</p> <p>Sendit may change the terms on this page. We will take steps to notify you when this occurs, but you are responsible for staying up-to-date with these changes.</p>",
                    "@keys": ["value"],
                    "@flat": true,
                    "@initialValue": {
                      value:
                        "<p>By using Sendit, you agree to the terms and conditions listed on this page.</p> <p>Sendit may change the terms on this page. We will take steps to notify you when this occurs, but you are responsible for staying up-to-date with these changes.</p>",
                    },
                  },
                  "@keys": ["heading", "description"],
                  "@flat": false,
                  "@initialValue": {
                    heading: "Sendit Terms And Conditions",
                    description:
                      "<p>By using Sendit, you agree to the terms and conditions listed on this page.</p> <p>Sendit may change the terms on this page. We will take steps to notify you when this occurs, but you are responsible for staying up-to-date with these changes.</p>",
                  },
                },
                {
                  "@id": "2c8ba44d-4a17-4d41-827b-95c4160f10c4",
                  heading: {
                    "@id": "content_blocks.terms_and_conditions.heading",
                    value: "Account Information & Payments",
                    "@keys": ["value"],
                    "@flat": true,
                    "@initialValue": {
                      value: "Account Information & Payments",
                    },
                  },
                  description: {
                    "@id": "content_blocks.terms_and_conditions.description",
                    value:
                      "<ul><li>Fees must be paid at or before the date specified in your payment plan.</li> <li>Failure to pay account fees may result in restricted or suspended access to your Sendit account.</li></ul>",
                    "@keys": ["value"],
                    "@flat": true,
                    "@initialValue": {
                      value:
                        "<ul><li>Fees must be paid at or before the date specified in your payment plan.</li> <li>Failure to pay account fees may result in restricted or suspended access to your Sendit account.</li></ul>",
                    },
                  },
                  "@keys": ["heading", "description"],
                  "@flat": false,
                  "@initialValue": {
                    heading: "Account Information & Payments",
                    description:
                      "<ul><li>Fees must be paid at or before the date specified in your payment plan.</li> <li>Failure to pay account fees may result in restricted or suspended access to your Sendit account.</li></ul>",
                  },
                },
              ],
              "@keys": ["value"],
              "@flat": true,
              "@initialValue": [
                {
                  heading: "Sendit Terms And Conditions",
                  description:
                    "<p>By using Sendit, you agree to the terms and conditions listed on this page.</p> <p>Sendit may change the terms on this page. We will take steps to notify you when this occurs, but you are responsible for staying up-to-date with these changes.</p>",
                },
                {
                  heading: "Account Information & Payments",
                  description:
                    "<ul><li>Fees must be paid at or before the date specified in your payment plan.</li> <li>Failure to pay account fees may result in restricted or suspended access to your Sendit account.</li></ul>",
                },
              ],
            },
            "@keys": ["_bookshop_name", "terms_and_conditions"],
            "@flat": false,
            "@initialValue": {
              _bookshop_name: "privacy",
              terms_and_conditions: [
                {
                  heading: "Sendit Terms And Conditions",
                  description:
                    "<p>By using Sendit, you agree to the terms and conditions listed on this page.</p> <p>Sendit may change the terms on this page. We will take steps to notify you when this occurs, but you are responsible for staying up-to-date with these changes.</p>",
                },
                {
                  heading: "Account Information & Payments",
                  description:
                    "<ul><li>Fees must be paid at or before the date specified in your payment plan.</li> <li>Failure to pay account fees may result in restricted or suspended access to your Sendit account.</li></ul>",
                },
              ],
            },
          },
        ],
        "@keys": ["value"],
        "@flat": true,
        "@initialValue": [
          { _bookshop_name: "privacy/hero", title: "Terms & Conditions" },
          {
            _bookshop_name: "privacy",
            terms_and_conditions: [
              {
                heading: "Sendit Terms And Conditions",
                description:
                  "<p>By using Sendit, you agree to the terms and conditions listed on this page.</p> <p>Sendit may change the terms on this page. We will take steps to notify you when this occurs, but you are responsible for staying up-to-date with these changes.</p>",
              },
              {
                heading: "Account Information & Payments",
                description:
                  "<ul><li>Fees must be paid at or before the date specified in your payment plan.</li> <li>Failure to pay account fees may result in restricted or suspended access to your Sendit account.</li></ul>",
              },
            ],
          },
        ],
      },
      "@keys": ["_schema", "title", "seo", "content_blocks"],
      "@flat": false,
      "@initialValue": {
        _schema: "default",
        title: "Privacy",
        seo: {
          page_description: null,
          canonical_url: null,
          featured_image: null,
          featured_image_alt: null,
          author_twitter_handle: null,
          open_graph_type: null,
          no_index: false,
        },
        content_blocks: [
          { _bookshop_name: "privacy/hero", title: "Terms & Conditions" },
          {
            _bookshop_name: "privacy",
            terms_and_conditions: [
              {
                heading: "Sendit Terms And Conditions",
                description:
                  "<p>By using Sendit, you agree to the terms and conditions listed on this page.</p> <p>Sendit may change the terms on this page. We will take steps to notify you when this occurs, but you are responsible for staying up-to-date with these changes.</p>",
              },
              {
                heading: "Account Information & Payments",
                description:
                  "<ul><li>Fees must be paid at or before the date specified in your payment plan.</li> <li>Failure to pay account fees may result in restricted or suspended access to your Sendit account.</li></ul>",
              },
            ],
          },
        ],
      },
    },
    initialDepth: [
      "@root",
      "content_blocks",
      "c41f6355-56b9-41ce-9cc3-e96a8ae46116",
    ],
    preventSettingFocusListener: true,
    isFullEditor: false,
    site: {
      stable_domain: "sturdy-soybean.cloudvent.net",
      domain_name: null,
      site_name: "sendit-astro-template",
      share_level: 0,
      user_id: 42636,
      password: "",
      site_icon_state: "full-bleed",
      connected: true,
      icon: null,
      empty: false,
      from_template: null,
      id: 115011,
      uuid: "80ea1115-1064-447e-8bb5-695ca4c2df62",
      authentication: null,
      auto_generate_ssl: true,
      automatic_builds_state: null,
      base_domain: null,
      base_domain_id: null,
      browsing_locked: false,
      build_configuration:
        '{"astro":{"preserved_paths":"node_modules/","environment_variables":[{"key":"PUBLIC_LIVE_RENDER","value":"true"}],"install_command":"npm install","build_command":"npm run build","output_path":"dist"},"jekyll":{}}',
      building_locked: false,
      client_editor_route: "update",
      cloudflare_hostname: null,
      cloudflare_hostname_uuid: null,
      compiler_order: ["compile", "i18n", "post-processing", "compressor"],
      created_at: "2023-08-11T20:14:48.178Z",
      default_locale: "en",
      delegated_hosting_site: null,
      destroy_on_publish: false,
      documentation_url: null,
      editing_locked: false,
      flags: null,
      force_extensionless: false,
      force_ssl: true,
      geolocation: false,
      has_client_password: false,
      has_form_hooks: false,
      has_site_password: false,
      hosting_choice: "cloudcannon",
      keep_form_hook_days: null,
      last_cleaned: null,
      last_compiled: "2023-08-11T20:15:56.575Z",
      last_compiled_success: "2023-08-11T20:15:56.575Z",
      last_compressed: null,
      last_internationalised: null,
      last_output: null,
      last_published: null,
      last_synced: "2023-08-11T20:14:59.356Z",
      latest_hosted_build_id: 14294029,
      latest_hosted_build_uuid: "6e23e3ad-c2b2-45ea-a189-31e355a459d7",
      main_source_dam: null,
      needs_clean: false,
      organisation_uuid: "cb2dcfff-abf4-4a47-bdb7-c5517800ddf5",
      output_error: null,
      output_storage_provider: null,
      output_storage_provider_data: {},
      prevent_client_password_save: false,
      preview_url: null,
      priority_domain_at: "2014-06-21T05:08:23.269Z",
      publish_mode: "merge",
      recaptcha_key: null,
      recaptcha_secret: null,
      saml_data: "{}",
      serve_extensionless: true,
      ssg: "astro",
      ssl_certificate: null,
      ssl_certificate_id: null,
      storage_provider: null,
      storage_provider_details: null,
      subpath: null,
      support_url: null,
      sync_error: null,
      updated_at: "2023-08-11T20:15:58.161Z",
      uploads_locked: false,
      uses_i18n: false,
      has_compiler_error: false,
      last_backup_start: "2023-08-11T20:16:11.666Z",
      "sync-state": "done-backup",
      last_backup_complete: "2023-08-11T20:16:14.054Z",
      last_synced_with_changes: "2023-08-11T20:14:59.368Z",
      last_compile_start: "2023-08-11T20:15:08.852Z",
      "build-state": "done-compile",
    },
    file: {
      path: "/src/content/pages/privacy.md",
      sent: false,
      selected: false,
      failed: false,
      uploaded: true,
      batched: true,
      finalised: true,
      progress: 0,
      errors: null,
      md5: "5d8eb3dc7b6d717eb38a79449043d7f7",
      size: 1,
      site_id: 115011,
      fetched: true,
    },
  },
};
